### PR TITLE
Improve dependency installing in install.sh

### PR DESCRIPTION
**Pull request by Itai-Nelken**
I renamed the `pkg-manager` function to `pkg-install`, and now it installs all the packages names provided to it using the system package manager (apt or pacman for now).
Then the if statments check if the packages aren't installed, if they aren't they are added to the array. then if the array isn't empty, the packages it contains are installed using the `pkg-install` function.
I did this because I think that installing all the packages at once is better then checking if one is installed, if no install it. then check for the next packacge, if it's not installed, install it etc.

### CODE REVIEW

**Comment by CleanMachine1** [comment]
I can't test this. Have you thoroughly tested?

**Comment by Itai-Nelken** [comment]
I tested it with pacman and it works. I'm 99% sure it will work with apt as well.

**Comment by CleanMachine1** [comment]
I don't feel like uninstalling git, make and gcc since fear it will remove my configuration and break my system. I could do it in VM though unless you're willing to.

**Comment by Itai-Nelken** [comment]
I removed git and make on my manjaro system, ran the install script, and it worked. I guess it should work the same with apt.

**Comment by CleanMachine1** [comment]
If you have tested on arch based, I've tested on ubuntu based then i am happy to merge, thanks. Rebased and applied

**Pull request merged**
